<main>
    <h2 style='margin-left: -5px;'>Tervetuloa palveltavaksemme!</h2>
       <p>
        Siru's Hairsaloon on pieni ja idyllinen parturi-kampaamo Helsingin keskustassa.<br>
        Tärkein tavoitteemme on saada sinulle leveä hymy kasvoillesi, tervetuloa!
       </p>
      <div class='space-div'></div>
     <div class="etusivu-kuva">       
      <img src="../public/images/kuva2.png" width='250px' height='250px' style='border-radius: 2rem' alt="Ai generated by Craiyon">
    </div>       
    <div class='space-div'></div>
    <?php include('../src/components/form.php') ?>
</main>
