<main>
    <h4>Siru' Hairsaloon, juuri sinun kauneuttasi varten!</h4>
      <p>
        Siru's Hairsaloon on vuonna 2005 perustettu parturi-kampaamo,<br>
        josta löydät avun silloin, kun kaipaat hiusten leikkausta tai värjäystä.<br>
        Meiltä saat avun myös silloin, kun haluat näyttävän kampauksen ja/tai meikin, niin arkeen kuin juhlaan.
      </p>
    <div class='space-div'></div> 
    <div class="meista-kuva1">       
      <img src="../public/images/kuva1.jpg" width='400px' height='250px' style='border-radius: 2rem;' alt="cc0" title='cc0-kuva'>
    </div>       
    <div class='space-div'></div>
    <h2>Keitä olemme</h2>
    <hr>
    <h4>Siru</h4>
    <div class="meista-kuva2">       
      <img src="../public/images/portrait1.png" width='200px' height='200px' style='border-radius: 1rem; margin-bottom: 5px' alt="Ai generated by Craiyon">
    </div>
      <p>
        Olen toiminut parturi-kampaajana vuodesta 2000 lähtien.<br>
        Siru'sin perustin vuonna 2005. Minulle on tärkeää voida toteuttaa<br>
        asiakkaan toiveet lämminhenkisessä ja kodikkaassa ympäristössä.<br>
        Olen erikoistunut muotoonleikkauksiin ja ihonsävyyn sopivien värien löytämiseen. <br>
      </p>
    <div class='space-div'></div> 
    <h4>Anne</h4>
    <div class="meista-kuva3">       
    <img src="../public/images/portrait2.png" width='200px' height='200px' style='border-radius: 1rem; margin-bottom: 5px' alt="Ai generated by Craiyon">
    </div>
      <p>
        Valmistuin parturikampaajaksi vuonna 2010 ja olen toiminut<br>
        Sirun tiimistä siitä lähtien. Voimani työpäiviin ammennan asiakkaista,<br>
        ja heidän mielenkiintoisista tarinoistaan! Olen erikoistunut värjäyksiin, <br>
        ja toteutan mielelläni villeimmätkin värjäystoiveet!
      </p>
    <div class='space-div'></div>
    <h4>Milla</h4>
    <div class="meista-kuva4">       
    <img src="../public/images/portrait3.png" width='200px' height='200px' style='border-radius: 1rem; margin-bottom: 5px' alt="Ai generated by Craiyon">
    </div>
      <p>
        Olen valmistunut parturi-kampaajaksi vuonna 2005 ja maskeeraajaksi<br>
        vuonna 2012. Sirulla aloitin vuonna 2018 ja teen pääasiassa meikkejä ja kampauksia,
        jotka ovatkin suuri intohimoni.<br>
        Jos Sirulla ja Annella on kalenterit täynnä, toteutan myös muita kampaamopalveluita.
     </p>
    <div class='space-div'></div><hr> 
</main>