<main>
  <h4>Hiusten leikkaukset ja värjäykset</h4>
    <p>
      Meiltä saat kaikki perinteiset parturi- ja kampaamopalvelut.<br>
      Toteutusten suhteen vain mielikuvitus on rajana ja teemmekin rohkeasti myös persoonallisia hiuksia.<br><br>
      Saat meiltä myös hiuksillesi ja uudelle värillesi sopivat kotihoito-ohjeet ja tuotteet.
   </p>      
    <div class='space-div'></div>
    <h4>Kampaukset ja meikit</h4>
    <p>
      Toteutamme kampaukset sekä meikin erityiseen päivääsi. <br>
      On kyse sitten suuresta juhlasta tai hienommasta illallistapaamisesta, toteutamme toiveesi.<br>
      Voit aina varata meille myös ajan pikameikkiin ja/tai -kampaukseen,<br>
      jolloin voimme tehdä tavallisesta arkipäivästäsikin hieman fiinimmän.
    </p>     
    <div class='space-div'></div>
  <div class="palvelut-kuva1">       
    <img src="../public/images/kuva3.png" width='200px' height='200px' style='border-radius: 1rem; margin-bottom: 5px' alt="Ai generated by Craiyon">
  </div>
  <div class="palvelut-kuva2">       
    <img src="../public/images/kuva4.png" width='200px' height='200px' style='border-radius: 1rem; margin-bottom: 5px' alt="Ai generated by Craiyon">
  </div> 
</main>
